### ISSUE TITLE
Auto-generate/majikally create SQL for standard CRUD operations.

### ISSUE THREAD

**Issue by jonwagner** [jonwagner/Insight.Database#192]
While prototyping, it's often handy to have the ORM handle the SQL for standard CRUD operations.

You should be able to:

* conn.Insert<T>(T t)
* conn.Insert<T>(IEnumerable<T> list)
* Update/UpdateList
* Delete/DeleteList (by PK fields) 
* Select/SelectList (by PK fields)
* Query/Find by properties
* Auto-join when you do Query<A, B>, etc.

**Comment by jonwagner** [comment]
All of you international people should send me a local beer as "incentive" to build this feature. :)

**Comment by jonwagner** [comment]
Please leave comments on the wiki:

https://github.com/jonwagner/Insight.Database/wiki/Insight-6

**Comment by jonwagner** [comment]
As cool as this would be, my current opinion is that the features would pull Insight further away from being a micro-orm. I'm going to hold off from these.

**Comment by alexdegrand** [comment]
I appreciate your effort and I'm thinking to use Insight.Database but I'm blocked due to lack of automatic CRUD operations.
Standard CRUD and Query operations is a must for any application. If I take my current project as sample, it has 40 tables in database. I have to create:
 a. 80 Sps for Insert/Delete
 b. ~ 100 SPs for update (each time you update small set of fields)
 c. ~ 100 SPs for select 
Furthermore,
 1. As developer, I'm exposed to errors
 2. Most of CRUD operations do not require high performance (it does not make difference for the end user when pushing a button in the UI if the update take 80 ms or 200 ms).
I think, you may reconsider your decision because Insight.Database is one of the best ORM I have checked.

**Comment by jonwagner** [comment]
If you’re using SQL Server, check out Insight.Database.Schema. It’s a schema migration engine that also automatically generates stored procs for you.

The general consensus is that adding automatic CRUD is outside the scope of Insight.Database and that it should be part of another (but compatible) project. I already have that running for SQL Server through Insight.Database.Schema. If I decide to support other database servers, I would do the work there.

If anyone wants to help with that, I’d appreciate it, as I’ve just started a new endeavor and my time is limited.

From:  alexdegrand
Reply-To:  "jonwagner/Insight.Database"
Date:  Monday, June 8, 2015 at 6:39 AM
To:  "jonwagner/Insight.Database"
Cc:  Jon Wagner
Subject:  Re: [Insight.Database] Auto-generate/majikally create SQL for standard CRUD operations. (#192)


I appreciate your effort and I'm thinking to use Insight.Database but I'm blocked due to lack of automatic CRUD operations.
Standard CRUD and Query operations is a must for any application. If I take my current project as sample, it has 40 tables in database. I have to create:
 a. 80 Sps for Insert/Delete
 b. ~ 100 SPs for update (each time you update small set of fields)
 c. ~ 100 SPs for select 
Furthermore,
As developer, I'm exposed to errors
Most of CRUD operations do not require high performance (it does not make difference for the end user when pushing a button in the UI if the update take 80 ms or 200 ms). I think, you may reconsider your decision because Insight.Database is one of the best ORM I have checked.

**Comment by alexdegrand** [comment]
Thank you for pointing me to Insight.Database.Schema.
I will try to help with the new compatible project if you can share with us some guideline/starting points.
In my understanding we need an sqlBuilder for CRUD operations and some connection.extensions
