### ISSUE TITLE
Castle.DynamicProxy issues on auto-implemented classes and interfaces

### ISSUE THREAD

**Issue by resnikb** [jonwagner/Insight.Database#213]
Hi, This is the same in nature with issue #148, this time when mixing auto-generated classes and interfaces. The cause, as much as I can tell, is the duplicate name of the generated assembly. This test fails with the latest version of Insight (does not depend on Castle):

        [Test]
        public void CanGetGeneratedTypeByName()
        {
            var i1 = Connection().As<IProxyTarget>();
            var i2 = Connection().As<IProxyTargetOther>();

            var t = Type.GetType(i2.GetType().AssemblyQualifiedName);

            Assert.That(t, Is.SameAs(i2.GetType()));
        }

Changing the assembly name in InterfaceGenerator fixes both the test and DynamicProxy issue:

    AssemblyName an = new AssemblyName { Name = "Inisght.Database.Generated" };

Cheers,
Bojan

**Comment by jonwagner** [comment]
Thanks. I'm swamped at the moment. If you put in a pull request, I can do a build.

**Comment by jonwagner** [comment]
I ran your test case, and your suggested change fails to fix it.

Type.GetType will always return null with dynamically generated assemblies. See https://msdn.microsoft.com/en-us/library/w3f99sx1(v=vs.110).aspx

I can change the name of the generated assembly if it fixes a few things, but I'd have to do it in the 6.0 branch, since it would force people to change their InternalsVisibleTo attributes.

Of course, I'd still like to have a test case that illustrates this issue. Can you think of another way to repro it, or maybe post some Castle code or exceptions?

**Comment by resnikb** [comment]
Since opening the issue, I've upgraded to Windows 10 and VS2015, and, as you've pointed out, the test no longer works, and, whats more, I can't reproduce my original issue anymore. While I am aware of Type.GetType behavior, I am certain the test case was fully consistent and reproducible before.

Now, I can only suggest that you rename the assembly, as having two different assemblies with exact same names, versions and tokens seems like it might cause issues, but I can't actually prove that it does.

Thanks for looking into it!

**Comment by jonwagner** [comment]
I'm going to close this for now. Let me know when you break it again!
