### ISSUE TITLE
PostgreSQL JSONB - InvalidDataContractException

### ISSUE THREAD

**Issue by edburgos** [jonwagner/Insight.Database#239]
I'm getting the following error:

>An unhandled exception of type 'System.Runtime.Serialization.InvalidDataContractException' occurred in System.Runtime.Serialization.dll

>Additional information: Type 'ConsoleApplication1.Program+TestData' cannot be serialized. Consider marking it with the DataContractAttribute attribute, and marking all of its members you want serialized with the DataMemberAttribute attribute.  If the type is a collection, consider marking it with the CollectionDataContractAttribute.  See the Microsoft .NET Framework documentation for other supported types.

I Installed Insight.Database.Providers.PostgreSQL via Nuget (latest, 5.2.7.0) along with NpgSql 3.0.4.0

I tried running the exact piece of code found in the [PostgreSQL Unit Test](https://github.com/jonwagner/Insight.Database/blob/master/Insight.Tests.PostgreSQL/PostgreSQLTests.cs#L470) and I got the error:

    _connection.ExecuteSql(@"CREATE TABLE Users (Id integer NOT NULL, JsonData jsonb)");
    _connection.ExecuteSql("CREATE TYPE PostgreSQLTestType AS (Id integer, JsonData jsonb)");
    _connection.ExecuteSql(@"
        CREATE OR REPLACE FUNCTION PostgreSQLTestExecute (Id integer, JsonData jsonb) 
        RETURNS SETOF PostgreSQLTestType
        AS $$
        BEGIN 
        	RETURN QUERY SELECT id as id, JsonData as JsonData;
        END;
        $$ LANGUAGE plpgsql;");
    
    var result = _connection.Query<UsersWithTestData>("PostgreSQLTestExecute", users).First();

Also tried moving NpgSql version to 2.2.5 which seems to be the one used in the Unit Tests and still got the same error.

**Comment by Jaxelr** [comment]
Hi Ed,

Loaded the test project from Insight.Test.Postgresql proj, ran the nunit console and all tests passed. However, i also made a console app (since your error shows you used a console app) and managed to emulate your error. The problem seems to happen with the serialization of the [TestData](https://github.com/jonwagner/Insight.Database/blob/master/Insight.Tests.PostgreSQL/PostgreSQLTests.cs#L32)  class inside the TestFixture. Managed to work around it by adding the attributes of DataContract and DataMember to the Class that can be used from the System.Runtime.Serialization library. 


```
        [DataContract]
        public class TestData
        {
            [DataMember]
            public int X;

            [DataMember]
            public int Z;
        }
```

Hope this helps, and sorry for the delayed answer.

**Comment by jonwagner** [comment]
Good call @Jaxelr 

By default, Insight uses the JsonSerializer in the .NET library, and that requires DataContract attributes.

The other option would be to enable the JsonNetSerializer by installing Insight.Database.Json

See the wiki in /Object-Serialization for details on enabling that.

That should resolve your issue. Please re-open if you need any more help.
