### ISSUE TITLE
Returning boolean values from stored process

### ISSUE THREAD

**Issue by joshka** [jonwagner/Insight.Database#241]
Hi,
In order to return a boolean value from a stored procedure (with the automatic interface generation), it is necessary to cast your column result to a bit.
e.g.
```
SELECT CAST(1 AS bit)
```
Not doing so throws a SpecifiedCastIsInvalidException at https://github.com/jonwagner/Insight.Database/blob/09c374cac9017cc2cf4238aff9cc2ed94e01f49e/Insight.Database/Extensions/DBConnectionExtensions.cs#L1593
A quick solution is to call `Convert.ChangeType(result, typeof(T))` instead of `(T)result` there, which may be sufficient for some use cases. Does this fall over for databases that don't support boolean types?

A more thorough solution is to support Serialization on results. I'm not sure whether that would be worth the effort. Thoughts?

**Comment by kevinsea** [comment]
I think this is expected behavior.  Your interface should reflect the type being returned from the database.   If you want the interface to have a bool, you send back a bool.  Insight will do some lossless conversion, but not int to bool.

If I've totally  misunderstood your question, sorry.  If so, please reopen this issue with some more details.

**Comment by joshka** [comment]
@kevinsea, this was a while ago on a project I'm no longer involved with so I don't have the exact context. I was suggesting that coercing 0 and 1 to boolean was a fairly useful automatic conversion that would save a bit of repeated code at the db layer. I think your response is correct now that I read my request. Either way - no real need on my end anymore.

**Comment by kevinsea** [comment]
Thanks.  And sorry about about the slow reply!
