### ISSUE TITLE
Improve documentation for Custom Serializer Methods CanSerialize CanDeserialize

### ISSUE THREAD

**Issue by nzbart** [jonwagner/Insight.Database#250]
I tried to write a custom serialiser using [the documentation](https://github.com/jonwagner/Insight.Database/wiki/Object-Serialization#custom-serializers) as a guide, but found that I needed to add a `CanDeserialize` method before the serialiser was invoked. Is this required when using the `Column` attribute, or am I missing something?

On a positive note, I found the solution by downloading your code and looking through the tests - so kudos to you for writing such a comprehensive test suite!

**Comment by schmalls** [comment]
I also had to override the CanSerialize method. It isn't required because there is an implementation in the base class, but it looks like in both of our scenarios that the default implementation was not good enough. At a minimum, I think we need to update the documentation to reflect that this may be required.

**Comment by jonwagner** [comment]
Done.
