### ISSUE TITLE
How to do split tables and heirarchies TPH with Insight

### ISSUE THREAD

**Issue by weedkiller** [jonwagner/Insight.Database#290]
Hi I am considering using Insight - looks awesome, wondering if its still supported and if theres a roadmap

Now to the issue - for e.g. to keep the user table light weight is there support _create_/maintain/CRUD and query split tables

Unable to handle both Table-splitting and Table per hierarchy ([TPH](https://weblogs.asp.net/manavi/inheritance-mapping-strategies-with-entity-framework-code-first-ctp5-part-1-table-per-hierarchy-tph)) and [here](https://datatellblog.wordpress.com/2015/04/12/inheritance-modelling-patterns-with-entity-framework-6-code-first/)

What is a EF split table, see [this](http://stackoverflow.com/questions/21033452/ef6-failing-to-build-model-for-table-split-shared-primary-key-base-class), [this ](https://visualstudiomagazine.com/articles/2014/09/01/splitting-tables.aspx) and [this](http://www.c-sharpcorner.com/UploadFile/ff2f08/entity-splitting-in-entity-framework-6-code-first-approach/)

So EF only loads main user profile table for speed, but you can also say UserProfile.Include("ExtendedUserHealthRecordsOrEMployeeRecsEtc").

Since the user table is used extensively and needs to be fast, while also holding more user information, we adopted the EF table splitting. EF and SQL lets us do table splitting or split tables natively, for e..g. we have extended with more fields the identiy user profile, and to speed it up we have used split tables.

**Comment by kevinsea** [comment]
Entity Framework and Insight are quite different philosophically.  Entity comes with a big performance cost: in time per row read and network use.  The last I looked at EF it was 5-10X slower reading rows.  And it generated flat queries for object hierarchies greatly increasing data over the wire.

The micro-orm approach is to have your (Insight) repository do simple CRUD operations that return repo scoped objects.  You would then use those objects to instantiate domain objects, often using an auto-mapper library (dividing repo objects and domain objects is recommended by many people anyways).  You write a bit more code, but your code is fast.  Having used EF before in production, I would choose any micro-ORM before EF, YMMV.

Roadmap: we are definitely coming out of a bit of lull, but there are several people actively on .Net Core compatibility - that may not be apparent since its happening in my fork.  

There are several good micro-ORM's out there.  Where Insight shines is:
- Speed (mappers are generated IL)
- Auto-maps object hierarchies (I think this is rare in the micro space)
- Intelligent mapping of objects to stored procedures (some micro orm's just assume every public property on your C# object is a parameter on your proc - this can be a huge headache while rolling out a release)
- Good code coverage
- Good documentation (that also lists more great features)

**Comment by kevinsea** [comment]
Actually you could use a MultiReader to do this, see /wiki/Record-Readers.

**Comment by jonwagner** [comment]
Still supported. Just being slow. :)

You can do table-splitting with Insight. You'll be writing your own sprocs (or use some of the autoprocs in Insight.Database.Schema if you're using sql server).

Insight will automatically map whatever parameters match between your object and the proc, or your object and the recordset.

Personally, I'd rather write my own procs than have them generated. Any time I use a framework that generates SQL for me, it always turns into a performance issue at some point.

Feel free to ask questions here if you have any more.
