### ISSUE TITLE
Structs are not handled correctly inside table valued parameters

### ISSUE THREAD

**Issue by jamezor** [jonwagner/Insight.Database#292]
As per failing test in 20b6bf53c62f05c954f42255d5c983ea3005f8f2 it looks like the handling of structs when included as properties in table valued parameters is not correct.

I think this is due to lines 129 - 143 in Insight.Database\CodeGenerator\ObjectReader.cs where value types are excluded from the serialisation; this is all part of some rather hairy IL emission though so I'm not 100% sure if that is the cause.

**Comment by kevinsea** [comment]
Sorry for the delay.

IL is tough.  

It does seems like we'd always want to try to serialize a struct, they just get lost because they are a non-standard value type and there is not type.IsStruct.  I believe changing this line would change the behavior only for structs: 

`if (sourceType != targetType  &&  !sourceType.IsValueType  &&  sourceType != typeof(string))`

I think the fix would be to change IsValueType to IsPrimitive and IsEnum :

`if (sourceType != targetType && !sourceType.IsPrimitive && !sourceType.IsEnum &&
					    sourceType != typeof(string))`

Want to try it?

**Comment by jonwagner** [comment]
This is fixed in 5.2.9
