### ISSUE TITLE
Does Insight.Database inherit [Sql] annotations?

### ISSUE THREAD

**Issue by rwgbryant** [jonwagner/Insight.Database#293]
As per the stackoverflow thread [here](Does Insight.Database inherit [Schema] annotations?), I thought I'd try something a bit clever/stupid in my datalayer. Since most of my tables have a set of CRUD operations, I figured, why not do this :

`public interface IDataInterface<T>
{
    Task<T> SelectAsync(int id);

```
Task<IEnumerable<T>> SelectAsync();

Task<int> UpsertAsync(T obj);

Task<bool> UpsertManyAsync(IEnumerable<T> list);

Task<bool> DeleteAsync(int id);

Task<bool> DeleteManyAsync(IEnumerable<T> list);
```

}

```

And then use it like this - 


[Sql(Schema  = "Clients")]
public interface IClientDataInterface : IDataInterface<Client>
{

}
```

where all sprocs related to Clients table sit in the Clients schema.  Sneaky, huh?  But it doesn't work.

`InnerException = {"The stored procedure 'Upsert' doesn't exist."}`

But Clents.Upsert definitely exists.  I know.  I wrote it.

Is there any way I can make this work?

**Comment by Jaxelr** [comment]
I can confirm that Insight doesnt inherit the Attribute SQL. https://github.com/jonwagner/Insight.Database/blob/04bcf2a2ad4ea08f6c6722b791d646aa467341ac/Insight.Database/SqlAttribute.cs#L13

Since you cant generically use the SQL attribute inside the Generic Interface, you will probably have to resort to some reflection to get this done, which is neither pretty nor performant. GL tho!
