### ISSUE TITLE
Cancel long running querys?

### ISSUE THREAD

**Issue by madrianr** [jonwagner/Insight.Database#338]
Hello,

How to cancel long running querys?

robert

**Comment by jonwagner** [comment]
For synchronous queries, you would need to call `SqlCommand.Cancel`. (See https://msdn.microsoft.com/en-us/library/system.data.sqlclient.sqlcommand.cancel(v=vs.110).aspx)  Since Insight hides most of this from you, I don't recommend this approach.

For asynchronous queries, you can pass in a cancellation token:

    CancellationToken token;
    var task = connection.FooAsync(token); // runs the query in a task
    token.Cancel(); // will cancel the operation

Another option is to set the commandTimeout property. You can do that on the connection string or on a per command basis (see commandTimeout in the Insight wiki).

**Comment by madrianr** [comment]
In ASP.NET Core there are some Problems with the CancellationToken and I therefore I use  synchronous queries...
Do I have to use SQLCommand instead (like in the sample) or is it possible to access the Command from Insight for using  SqlCommand.Cancel?

robert

**Comment by jonwagner** [comment]
Your options are:

1. Use CommandTimeout. You can set the command timeout a few different ways. See https://github.com/jonwagner/Insight.Database/search?q=commandtimeout&type=Wikis&utf8=%E2%9C%93 and https://github.com/jonwagner/Insight.Database/wiki/Common-Method-Parameters

2. Create your commands manually (https://github.com/jonwagner/Insight.Database/wiki/Creating-Commands)

**Comment by madrianr** [comment]
Perfect - thank you
