### ISSUE TITLE
Multiple level children

### ISSUE THREAD

**Issue by MoeHamdan** [jonwagner/Insight.Database#366]
## Type
What kind of issue is this?

```
[ ] Bug report.
[X ] Feature request.
```
## Current Behavior

I do not know how to implement it, not sure if it is there.

## Expected behavior

I need to fill multiple levels using the interface mechanism.

## Steps to Reproduce

Let us assume we have Class A, B and C.

`public class A {public List<B> {get;set;}
public class B {public List<C> {get;set;}
public class C {}
`
So I am returning A using an interface method that will be using a stored procedure, however the Recordset attribute does not seem to have the parents property so I could properly map C.

Kindly advise
### Any other comment

(n/a)

**Comment by Jaxelr** [comment]
**Caveat:** This is not the specific answer you are looking for.

I've ran into this situation on several occasions when using Auto Interface Implementations, what i usually do is i convert my interface into an abstract class and declare the method using Insight's abstract class management [see here...](https://github.com/jonwagner/Insight.Database/wiki/Auto-Interface-Implementation#abstract-class-implementation)

Like so:
``` c#
public abstract class HelloRepo
{
	public abstract IDbConnection GetConnection();

        //Implemented by Insight.
	[Sql("SELECT 1 ParentId, 'Parent' Name, 'Last Parent' SecondName")]
	public abstract Parent GetParent();

	public IEnumerable<Parent> GetParentChild() =>
		GetConnection().Query(@"
		SELECT 1 ParentId, 'Parent' Name, 'Last Parent' SecondName
    		SELECT 1 ParentId, 4 ChildId, 'Child' ChildName, 'Last Child' SecondChildName
			SELECT 4 ChildId, 6 GrandChildId, 'Grand Child' GranChildName, 'Grand Child Last' SecondGrandChildName",
			Parameters.Empty, Query.Returns<Parent>()
			.ThenChildren(Some<Child>.Records)
			.ThenChildren(Some<GrandChild>.Records, parents: p => p.Childs, into: (p, c) => p.GrandChild = c), 
			CommandType.Text);
}

public class Parent
{
	public int ParentId { get; set; }
	public string Name { get; set; }
	public string SecondName { get; set; }
	public IEnumerable<Child> Childs { get; set; }
}

public class Child
{
	public int ChildId { get; set; }
	public string ChildName { get; set; }
	public string SecondChildName { get; set; }
	public IEnumerable<GrandChild> GrandChild { get; set; }
}

public class GrandChild
{
	public int GrandChildId { get; set; }
	public string GranChildName { get; set; }
	public string SecondGrandChildName { get; set; }
}
```

Hope this helps!

**Comment by MoeHamdan** [comment]
Hello @Jaxelr 

Thank you for you reply. However I would prefer if there is an option for the auto interface.

**Comment by MoeHamdan** [comment]
Thank you @jonwagner

**Comment by jonwagner** [comment]
This seems possible. I'm going to take a shot at it.

**Comment by jonwagner** [comment]
I pushed a commit up to master that should support most use cases. Can you do a build and see if it works for you?

**Comment by MoeHamdan** [comment]
Thank you @jonwagner I will check it out

**Comment by MoeHamdan** [comment]
Hello @jonwagner 

Thank you mate! appreciate it! It is working as expected you may release it 👍

**Comment by jonwagner** [comment]
After Insight gets a recordset, it uses the Parents and Into functions to attempt to put child records into a property of the right object. If you use the Query.Returns<>.ThenChildren syntax, you have full flexibility to specify those methods. If you use interface generation, there are some limitations. For example `Into="What"` is translated directly to `parent.What.Add(child)` and `Parents=What` is translated to `parents = root.What`.

When a child is inserted, something like this happens:

```
root = first query;
parents = root.Parents;
parent = parents.Find (p => p.ID = child.ParentId)
parent.Into.Add(child)
```

Using Parents and Into should let you put grandchildren in the proper place.

For your example:

```
// assume that the ID fields are set up properly, otherwise you might need ID or ParentID properties in the attributes

class Client {
    public List<Scope> Scopes;
    public List<Resource> Resources;
}

class Scope {
    public List<Claim> Claims;
}

class Resource {
    public List<Claim> Claims;
}

CREATE PROC GetClient (ClientID [int])
SELECT FROM Clients;
SELECT FROM Clients JOIN Scopes;
SELECT FROM Clients JOIN Scopes JOIN Claims;
SELECT FROM Clients JOIN Resources;
SELECT FROM Clients JOIN Resources JOIN Claims;

public interface IClientRepo {
    [Recordset(0, Type=typeof(Client)]
    [Recordset(1, Type=typeof(Scope), Child=true] // automatically figures out Into=client.Scopes
    [Recordset(2, Type=typeof(Claim), Child=true, Parents="Scopes"] // automatically figures out scopes.Claims
    [Recordset(3, Type=typeof(Resource), Child=true] // automatically figures out Into=client.Resources
    [Recordset(4, Type=typeof(Claim), Child=true, Parents="Resources"] // automatically figures out Into=client.Resources
    public Client GetClient(int clientId);
}
```

Adding the Parents function makes grandchildren work, but great-grandchildren will take some additional work on your part.

For your example, if Claims has it's own children, it gets tricky.

```
CREATE PROC GetClient (ClientID [int])
-- ...first 5 recordsets
SELECT FROM Clients Join Scopes JOIN Claims JOIN ClaimDetails

public interface IClientRepo {
    // ...first 5 recordset attributes
    [Recordset(5, Type=typeof(ClaimDetail), Parents="???"]
    public Client GetClient(int clientId);
}
```

Since we're binding the interface to return a root object of type `Client`, there's currently no method exposed on Client that gets you to the proper parents of the ClaimDetail.

Using Jaxel's suggestion, you could write your own method to handle great-grandchildren.

I don't know if I'd spend too much time trying to get great-grandchildren out of a database in a single shot. My "feels" tells me that there is probably a better way.

In any case, the parents functionality is in v6.2.2 on NuGet now.
