### ISSUE TITLE
Looking for Sample Project 

### ISSUE THREAD

**Issue by sergioza** [jonwagner/Insight.Database#375]
Hi,

Trying to eval Insight.Database, so i wonder if there are any sample projects available using Insight.Database?

and also

How Insight.Database functionality different/advantageous vs Dapper?
Does it also provide any CRUD methods not to simplify basic CRUD operations instead of submitting SQL or SPs?

Many Thanx

**Comment by jonwagner** [comment]
Have you seen the documentation at the wiki?

https://github.com/jonwagner/Insight.Database/wiki

**Comment by sergioza** [comment]
Thank You Much Jon,

Documentation is very good, i thought that there might be some sample project additionally.
and also
How Insight.Database functionality different/advantageous vs Dapper (another common micro ORM)?
Does it also provide any CRUD methods not to simplify basic CRUD operations instead of submitting SQL or SPs?

Many Thanx

**Comment by Jaxelr** [comment]
If you are looking for some basic performance comparison, i added Insight into this [OrmBenchmark repo](https://github.com/InfoTechBridge/OrmBenchmark). It does include Dapper, Ef, petapoco, massive, simpledata, to name a few. 

In my opinion Insight shines through on:

- The need for complex result sets, while also maintaining the integrity of a SQL database. Why? The API is succinct and readable by a team. 
- if you want to avoid ceremony for basic stuff (like POCO crud).

**Comment by jonwagner** [comment]
One of the reasons Insight is so elegant is that we built it assuming that you would have some control over the object model and the stored procedures. That lets us have some really nice features without having to have complicated mapping or SQL generation rules.

I think we can support this use case. I opened a new issue to track it.

Since you found the sample code, I'll close this out, but you can follow #378 for the new feature.
