### ISSUE TITLE
MissingMethodException

### ISSUE THREAD

**Issue by isaacadams** [jonwagner/Insight.Database#408]
# Describe the bug

Our team is experiencing the following exception in our staging environment

`MissingMethodException: Method not found: 'Void Insight.Database.DbConnectionWrapper..ctor(IDbConnectioSystem.Collections.Generic.IDbConnection)'.`

The stack trace shows that the last method it entered was a runtime generated constructor of the interface we passed into the As<IOurInterface>(DbConnection) method.

## Steps to reproduce

This only occurs in our staging environment, so it is unclear how to reproduce it.

To make matters worse, after some time, the issue will go away. But it consistently comes back.

## Expected behavior

A implementation of one of our interfaces should be created based on the given connection to out database.

- Dotnet version: netcore2.1
- SDK: 2.1.401
- Database: SQL Server
- Library version: 6.2.8

**Comment by jonwagner** [comment]
Given that there are two open missing method issues, I’m starting to think that .net core has some stability issues with IL generation.

What version of .net core are you using?

On Nov 4, 2019, at 12:42 PM, Isaac Adams <notifications@github.com> wrote:

﻿
Describe the bug

Our team is experiencing the following exception in our staging environment

MissingMethodException: Method not found: 'Void Insight.Database.DbConnectionWrapper..ctor(IDbConnectioSystem.Collections.Generic.IDbConnection)'.

The stack trace shows that the last method it entered was a runtime generated constructor of the interface we passed into the As(DbConnection) method.

Steps to reproduce

This only occurs in our staging environment, so it is unclear how to reproduce it.

To matters worse, after some time, the issue will go away. But it consistently comes back.

Expected behavior

A implementation of one of our interfaces should be created based on the given connection to out database.

  *   Dotnet version: netcore2
  *   Database: SQL Server
  *   Library version: 6.2.8

**Comment by isaacadams** [comment]
@jonwagner we are using netcoreapp2.1 and the SDK we build on is 2.1.401

**Comment by resnikb** [comment]
@isaacadams The error message looks wierd - are you sure the constructor argument reported is of type `IDbConnectioSystem.Collections.Generic.IDbConnection` and not `System.Data.IDbConnection`?

**Comment by isaacadams** [comment]
@resnikb I am certain. On top of that, the `IDbConnectioSystem...` looks like a spelling error as if I am missing an "n" in the word "Connection". However I am typing the the exception details exactly as I received them and that is exactly, character for character, what it stated.

**Comment by isaacadams** [comment]
![staging error (1)](https://user-images.githubusercontent.com/26559009/68440305-94b88980-0198-11ea-8ab2-3caa69654a3c.png)

**Comment by isaacadams** [comment]
![staging error (1) copy](https://user-images.githubusercontent.com/26559009/68440352-c29dce00-0198-11ea-93fb-7bd22becec90.png)

**Comment by isaacadams** [comment]
The following exception occurred in the Insight.Database source code today, seemingly also related to runtime code generation.

![E82EBBAA-4F79-4056-8415-93CD22A2D4F7](https://user-images.githubusercontent.com/26559009/68440514-4952ab00-0199-11ea-8909-01abc06c3ecb.png)

**Comment by nwpz** [comment]
I am seeing this issue as well in 2.1 and 2.2 code bases. It's intermittent and usually recycling the app pool corrects it but I was hopping to find a solution here :)

MissingMethodException: Method not found: 'Void Insight.Database.DbConnectionWrapper..ctor(IDbConnectioSystem.Collections.Generic.IDbConnection)'.

**Comment by jonwagner** [comment]
@resnikb identified an area where the interface generator code was not thread-safe. this should be fixed in v6.2.11.

**Comment by nwpz** [comment]
Thanks, I’ve been using a build with that code for close to a week without
issue.
