### ISSUE TITLE
Please add support for Microsoft.Data.SqlClient

### ISSUE THREAD

**Issue by bart-degreed** [jonwagner/Insight.Database#424]
When switching from System.Data.SqlClient to the new Microsoft.Data.SqlClient library (https://devblogs.microsoft.com/dotnet/introducing-the-new-microsoftdatasqlclient/), existing code breaks with the next error:

```
Cannot derive parameters for the stored procedure dbo.CreateUser. Have you loaded the provider that supports SqlCommand?

   at Insight.Database.Providers.InsightDbProvider.DeriveParametersFromStoredProcedure(IDbCommand command)
```

Reason: Our customers are asking to enable the Always Encrypted feature, which was not available to .NET Core until now.

Environment: ASP.NET Core 3.1 on Windows 10

**Comment by Jaxelr** [comment]
I am guessing the correct implementation of this will be using a Provider akin to the  Insight.Database.Providers.* that currently exist on the repository. Since Microsoft.Data.SqlClient targets netstandard 2.0 that would mean that usage on 4.5.* would be out.

I did manage to replace on the default provider and at least in my initial tests it did worked.

**Comment by jonwagner** [comment]
Yup - my expectation is that we just duplicate the provider code and swap out the namespace.

**Comment by Jaxelr** [comment]
Ill take a stab during the weekend.
