### ISSUE TITLE
SqlException - Must declare the table variable when combining declare statements and lists of User defined table types 

### ISSUE THREAD

**Issue by michael-wolfenden** [jonwagner/Insight.Database#426]
# Describe the bug

Given the following

```csharp
async Task Main()
{
	SqlInsightDbProvider.RegisterProvider();
	
	var database = new SqlConnection("some_connection_string").As<IMyDatabase>();
	
	var guidInts = new [] {
		new GuidIntTable { 
			GuidValue = Guid.Empty,
			IntValue = 1
		}
	}.ToList();

	await database.ThisIsOk(guidInts).Dump();

	// Throws a sql exception -> Must declare the table variable "@guidInts".
	await database.ThisThrowsAnError(guidInts).Dump();
}

public interface IMyDatabase
{
	[Sql(@"
    select IntValue from @guidInts
	")]
	Task<int> ThisIsOk(List<GuidIntTable> guidInts);

	[Sql(@"
    declare @i int = 1
    select IntValue from @guidInts
	")]
	Task<int> ThisThrowsAnError(List<GuidIntTable> guidInts);
}

public class GuidIntTable
{
	public Guid GuidValue { get; set; }
	public int IntValue { get; set; }
}
```

The call to `ThisThrowsAnError` throw a `SqlException` with the message `Must declare the table variable "@guidInts"`

## Steps to reproduce

See above

## Expected behavior

No exception to be thrown

- Dotnet version: [netcore]
- Database: [SQL Server]
- Library version: [6.2.11]

**Comment by Jaxelr** [comment]
[Per wiki](https://github.com/jonwagner/Insight.Database/wiki/Query-Parameter-Mapping#special-case-single-enumerable)
 

> If you pass an IEnumerable in as the parameter object, Insight will assume that you want to turn it into a table-valued parameter. So it will look at the parameter list to find a TVP, and map the enumerable to that parameter. See Identity Inserts for an example.

What this means is that you need some sort of Type as Table in order to resolve the parameter when the datatype is anything that inherits from IEnumerable. Take a [look at this link](https://github.com/jonwagner/Insight.Database/wiki/Identity-Inserts) for usage samples.

**Comment by michael-wolfenden** [comment]
@Jaxelr I have the table type in the database, and as you can see the `ThisIsOk` method works fine. I get the exception when I have an enumerable of tvp's AND the sql contains a `declare` statement

**Comment by jonwagner** [comment]
There are some subtleties when you attempt to do that with inline SQL. Since Insight doesn't have a schema to derive input parameters, it has to scan the inline SQL. In that case, I believe that it only executes the enumerable code if there is exactly one parameter. When you add the additional variable, I think it skips the code.

I think we can do some work to fix it. There are enough open things that I might take a day and work through them all. (Of course, I'm always appreciative of people helping tackle open issues...)

**Comment by Jaxelr** [comment]
@michael-wolfenden woops, saw what you mean. I would guess that the declare doesn't work because insight is trying to match to the first @ instance it finds, and so its matching to the i declaration, instead of @guidInts.

**Comment by jonwagner** [comment]
I looked at `InsightDbProvider.DeriveParametersFromSqlText`. I can't think of a way to filter out declared variables consistently without writing a pretty comprehensive SQL parser.

So I went with this approach:

```
    DECLARE /*NOBIND*/ @i int = 5; SELECT /*NOBIND*/ @i
```

Adding /*NOBIND*/ right in front of a variable will tell insight no ignore it.

**Comment by Jaxelr** [comment]
Ill add this feature to the wiki.

**Comment by andymac4182** [comment]
Thanks heaps for this @jonwagner :D you do some amazing work
