### ISSUE TITLE
Insertion of different nested objects

### ISSUE THREAD

**Issue by srigithub99** [jonwagner/Insight.Database#468]
Hi All, 
I know there is way to insert an object[Beer] or list of objects [ list of beers ]. But can we insert different objects [ Beer, Cake, Cookie ] or list of different objects ?? Since there is a provision of getting multiple result sets , is there a way for insertion too ? .
Any replies would be appreciated.

**Comment by jonwagner** [comment]
It depends on what you're trying to do:

- If you're using SQL Server (and some other databases) you could create a stored procedure that takes multiple lists of objects and process them separately.
- If all of the objects derive from the same class, then the mapping engine should be able to use fields from the base class.

**Comment by Jaxelr** [comment]
@srigithub99 you can get multiple result sets, see the [result structures](https://github.com/jonwagner/Insight.Database/wiki/Specifying-Result-Structures)  wiki page for more information. 

Insight is by design pretty flexible, therefore you can get all exotic using the [record readers](https://github.com/jonwagner/Insight.Database/wiki/Record-Readers#how-auto-mapping-works) to populate your objects too.
